FROM alpine:3.8

# 更新Alpine的软件源为国内（清华大学）的站点
RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main/" > /etc/apk/repositories

RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    bash-doc \
    bash-completion \
    && rm -rf /var/cache/apk/* \
    && /bin/bash

RUN echo 'alias ll="ls -alh"' >> /root/.bashrc
